### ISSUE TITLE
Support for other genomes.

### ISSUE THREAD

**Issue by jemilianosf** [ay-lab/dcHiC#10]
Hi, I was wondering if there are plans to add support for additional genomes (like Drosophila dm6 or Arabidopsis tair10). 

Thanks!

**Comment by ay-lab** [comment]
Hi jemilianosf,

Thanks for your suggestion, We will soon update dcHiC to accommodate the other genomes.

**Comment by jemilianosf** [comment]
Great! This will be very useful. Thanks for the great resource.
