### ISSUE TITLE
Issue with pandoc

### ISSUE THREAD

**Issue by Weiming113** [ay-lab/dcHiC#100]
Hi,

Thanks for developing dcHiC.
I encountered an issue with pandoc. The error information was at below:

Error in pandoc_self_contained_html(file, file) : 
  Saving a widget with selfcontained = TRUE requires pandoc. See here to learn more https://bookdown.org/yihui/rmarkdown-cookbook/install-pandoc.html
Calls: subcompartment ... <Anonymous> -> <Anonymous> -> pandoc_self_contained_html
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted

Could you please help me check it?

**Comment by Weiming113** [comment]
> sessionInfo()
R version 4.2.3 (2023-03-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur ... 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.3

**Comment by ay-lab** [comment]
This is something new! Can you run without the pandoc?

**Comment by Weiming113** [comment]
> This is something new! Can you run without the pandoc?

Thanks for your response. I have resolved it out. It cannot be run through without pandoc. But the pandoc should be installed using brew install pandoc.

**Comment by ay-lab** [comment]
Great to know that! Thanks.
