### ISSUE TITLE
functionsdchic install error

### ISSUE THREAD

**Issue by IcyYeyangchen** [ay-lab/dcHiC#101]
Hi，I installed all dependencies with conda in new environment. 
Everything is ready except for functionsdchic , with compilation

 error 
```
make: *** Makeconf:177: RcppExports.o] Error 1
ERROR: compilation failed for package 'functionsdchic'
```
attachment is my conda list. Could you please help me check out.
[dchic_condalist.txt](https://github.com/user-attachments/files/16202367/dchic_condalist.txt)
Thx in advance

**Comment by ay-lab** [comment]
Hi,

Can you please try out the option 2 for installation?

**Comment by IcyYeyangchen** [comment]
ok，thx for reply，I found something wrong with my gcc and gfortran. I will try again
