### ISSUE TITLE
Issue with running dcHiC

### ISSUE THREAD

**Issue by rkash** [ay-lab/dcHiC#102]
Hi,

I am trying to run dchic  using this command

Rscript dchicf.r --file input.txt --pcatype cis --dirovwt T --genome hg38

and getting the following error 
"Performing block wise correlation calculation	Error: upper value must be greater than lower value Execution halted"

I checked the input files which I created using the preprocessing code from the pacage.
And nere was no bins where start < end.

I also tried with --ebackgrnd=1 I am getting the same thing.
for --ebackgrnd=2

I am geting the following error 

Calculating expected counts from chromosome wise background
Error in aggregate.data.frame(lhs, mf[-1L], FUN = FUN, ...) : 
  no rows to aggregate
Calls: lapply ... aggregate -> aggregate.formula -> aggregate.data.frame
Execution halted

Can you please help with the issue.
Thanks in advance.

Thanks and Regards
Kaustav

**Comment by ay-lab** [comment]
Hi,

I guess your input is the matrix.txt file with 3 columns (Bin-i, Bin-j and Count-k). 

i-th (lower) value should be less than j-th (upper) value i.e. i < j. 

Can you please check if this condition is satisfied or not?

**Comment by rkash** [comment]
Hi,

Yes, I checked the matrix.txt file for all bin-i its  i < j.

Thanks and Regards
Kaustav

**Comment by rkash** [comment]
I am also getting this warring 
ld: warning: -pie being ignored. It is only used when linking a main executable

Is this something I should be worried about?

**Comment by ay-lab** [comment]
The last warning is something new to me. 
No one has yet posted such a warning! I also didn't see that.
I don't know what that means and how it's appearing. Perhaps a machine-specific issue?? 

Regarding your first issue, it is always the format of the Hi-C matrix. 

Do you mind sharing in brief how you processed the Hi-C data and retrieved the matrix?

**Comment by rkash** [comment]
Hi,

Thanks for the help.

I think this may be machine-specific. I was using a Mac, but I retried on Linux today, and Cis worked fine.
I think the other issue was Chr M, which did not have many contacts.

But I got a segmentation fault error when I tried trans.
I saw the same was reported in the last issue as well.

As for the .hic files, they were made by Juicer, and then I used the preprocess.py code to generate the matrix. After that, I removed Chr M, X, and Y.

Thanks and Regards
Kaustav

**Comment by ay-lab** [comment]
I need to check the trans calls. However, cis differential calls are generally used for the analysis. You're good to go.

**Comment by rkash** [comment]
Hi,

Thanks. Sure, I will try with cis calls and let you know if I face any issues.

One more thing, one of my .hic files was generated using the latest Juicer. I tried the preprocessing, but for this in Hi-C straw, I need to put Chr1 instead of 1 to make it work. Is this handled somehow in the preprocessing.py?

Thanks and Regards,
Kaustav

**Comment by ay-lab** [comment]
preprocessing.py also uses hicstraw. I am not sure if the newer version of hicstraw can handle it or not. 
You can check this issue posted before. Here I have mentioned another easy way to convert the .hic file into required format - 
https://github.com/ay-lab/dcHiC/issues/83

**Comment by rkash** [comment]
Hi Thanks this is helpfull now everting works I modified the preprocessing code and it works with the new version.

**Comment by ay-lab** [comment]
Great to hear that! I am now closing the issue.
