### ISSUE TITLE
Is the input data distance-normalized count or raw count? 

### ISSUE THREAD

**Issue by sotuamax** [ay-lab/dcHiC#105]
Hi,

I have some questions about the input data. I have both cool and hic format, and I can transform them to the required format for dchic. However, after reading the paper, it is clear that distance-normalized count is required for SVD decomposition. Should I provide distance-normalized matrix count as input? Or raw count data is also okay as the program can do the distance-normalization on the data. 

In addition, would any matrix normalization, like KR, ICE, recommended on the matrix count? 

Many thanks for your clarification. 

Best,

**Comment by ay-lab** [comment]
Hi, 

Please provide the raw count matrix as input. dcHiC will perform the distance normalization. 
We don't recommend any normalization. 
Thanks.

**Comment by sotuamax** [comment]
Thank you! 

Best,
