### ISSUE TITLE
questions about the chr substring in chromosome

### ISSUE THREAD

**Issue by biozzq** [ay-lab/dcHiC#12]
Dear,

I found that the chromosome text file does not include the "chr" substring in the chromosomes. The default chromosomes in `dihic.py` for human and mice genomes also do not have the "chr” substring. However, the chromosomes in goldenpathData and blacklist data have the "chr" substring. Does this will cause some problems when running dcHiC?

Best wishes,
zheng zhuqing

**Comment by biozzq** [comment]
This question has been commented before (https://github.com/ay-lab/dcHiC/issues/3), however, It's easy to misunderstand.

**Comment by ay-lab** [comment]
Hi!

Thank you for the clarifying note—this shouldn't cause any issues.
