### ISSUE TITLE
Error when using the latest version of dcHiC

### ISSUE THREAD

**Issue by biozzq** [ay-lab/dcHiC#13]
Dear all,

When running following command, the program will exit with the error, `No such file or directory: 'hmfa_chrRAW_10MF-1_exp_1.txt'`. However, I remember I can run without any errors about two months ago, after updating the version of dcHiC, now the program fails.

`python dchic/dchic.py -res 50000 -inputFile ${pre}.txt -parallel 6 -chrFile chr.txt -input 2 -genome mm10 -alignData goldenpathData -keepIntermediates 1 -blacklist mm10-blacklist.v2.bed`

```
Error in `[<-.data.frame`(`*tmp*`, m$tss > tskeep, "tskeep", value = "yes") : 
  missing values are not allowed in subscripted assignments of data frames
Calls: pcselect -> [<- -> [<-.data.frame
Execution halted
Traceback (most recent call last):
  File "dchic/run.py", line 323, in <module>
    dmfa_file = open(name, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'hmfa_chrRAW_10MF-1_exp_1.txt'
Error in `[<-.data.frame`(`*tmp*`, m$tss > tskeep, "tskeep", value = "yes") : 
  missing values are not allowed in subscripted assignments of data frames
Calls: pcselect -> [<- -> [<-.data.frame
Execution halted
Traceback (most recent call last):
  File "dchic/run.py", line 323, in <module>
    dmfa_file = open(name, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'hmfa_chrRAW_10MF-1_exp_1.txt'
Error in `[<-.data.frame`(`*tmp*`, m$tss > tskeep, "tskeep", value = "yes") : 
  missing values are not allowed in subscripted assignments of data frames
Calls: pcselect -> [<- -> [<-.data.frame
Execution halted
Traceback (most recent call last):
  File "dchic/run.py", line 323, in <module>
    dmfa_file = open(name, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'hmfa_chrRAW_10MF-1_exp_1.txt'
Error in `[<-.data.frame`(`*tmp*`, m$tss > tskeep, "tskeep", value = "yes") : 
  missing values are not allowed in subscripted assignments of data frames
Calls: pcselect -> [<- -> [<-.data.frame
Execution halted
...
```

Sincerely,
Zheng zhuqing

**Comment by ay-lab** [comment]
Hi There,

I just re-tested the latest release on local data and it worked fine. I don't think any updates from the past two months (just a few small bug fixes) would cause this. 

One thing might be the goldenPath data. In an earlier comment from January, your specified command was at 100kb resolution; this one is at 50kb. Since the goldenPath is binned at the resolution of download, you will need a new folder for this run.

**Comment by biozzq** [comment]
Dear @ay-lab 

Yes, you are right, this error is caused by the different resolution. However, I wonder that how to prepare the goldenPath GC/TSS data at specific resolution? Thank you.

Best wishes,
Zheng zhuqing

**Comment by ay-lab** [comment]
Thank you for raising this concern—this is an important thing to note. If you don't specify "-alignData" in the arguments, dcHiC will re-download the goldenPath data at the given resolution. I would run one chromosome standalone at the new resolution, have dcHiC download the data, and then run the rest using that directory.
