### ISSUE TITLE
Add covariates to the model

### ISSUE THREAD

**Issue by csijcs** [ay-lab/dcHiC#18]
Really great tool.

Is it possible to add a covariate to the model? Specifically I would like to add copy number as a covariate rather than make a cutoff and blacklist regions. Is there a simple way to do this?

Thanks so much

**Comment by ay-lab** [comment]
Hi,
Thanks for using the tool. This is a very interesting question but will require some extensive study. 
Have you just tried to simply normalize the counts based on their copy numbers and perform the dchic?
https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2256-5

**Comment by csijcs** [comment]
Thanks for the reply. I have used that methodology for CNV normalisation, but it works in conjunction with the iterative correction. So the resulting matrices are both ICE normalised and CNV normalized, and I thought for your methodology the input needed to be the raw matrices. If its ok to use ICE normalised matrices with dchic then I can give it a try.
