### ISSUE TITLE
File for -repParams missing chr Y

### ISSUE THREAD

**Issue by esebesty** [ay-lab/dcHiC#20]
I'm running an analysis where I have no replicates, and was following the [wiki](https://github.com/ay-lab/dcHiC/wiki/Running-dcHiC-Without-Replicates) instructions. However, analysis of chr Y failed, and I found out that it fails at [this line,](https://github.com/ay-lab/dcHiC/blob/master/dchic/diffcmp_pythonV.r#L35) as the [humanparams.txt](https://github.com/ay-lab/dcHiC/blob/master/files/humanparams.txt) file does not contain info on chr Y. This info also seems to be missing from the mouse file. Is this intentional (I'm not an expert on HiC analysis)?

**Comment by ay-lab** [comment]
Hello,

Yes— in our analysis, we omitted chromosome Y.  It is poorly mapped and compartments from this chromosome generally tend to look pretty bad. You can create your own replicate parameters with multiple chrY samples or simply omit it.

**Comment by esebesty** [comment]
OK, thanks!
