### ISSUE TITLE
General questions about changes in 3D organization of chromatin

### ISSUE THREAD

**Issue by biozzq** [ay-lab/dcHiC#23]
Dear @ay-lab 

I think this question should be a general question. As the changes in 3D organization of chromatin can lead to different levels of changing in genome organization, including AB, TADs, and loop. If one region have been identified as B->A switch, does it mean we will also find many changings at TADs or loop level when we have sufficient sequencing data? Could you kindly let me know your comments on this issues. Any comments from you will be highly appreciated.

Best regards,
Zheng zhuqing

**Comment by ay-lab** [comment]
Hi, this is an interesting question. I would say the answer is most probably yes. I like to think of compartments as the emergent property of chromosomal interactions.  So when a region switches from B i.e. nuclear lamin-associated region to A or to the center of the nucleus the underlying chromosomal interactions should also change. Check is paper https://www.sciencedirect.com/science/article/pii/S0092867418315617. This paper discusses a region critical for mouse neuronal differentiation from mESC to NPC stage. The region which involves DppA4/2 gene switches from A in mESC to B in NPC thus suppresses the gene expression. Now a detailed analysis of this region also shows a change in the TAD boundaries, specifically deleting few loops can force the switch from A to B even within mESC cells. Further test also confirms this property in a few of the other regions also. These are maybe very good examples but you get the point that how underlying loops influence the compartments switches.

**Comment by biozzq** [comment]
Dear @ay-lab 

Thank you for such a helpful comment, I will read the literature you mentioned.

Best regards,
Zheng zhuqing
