### ISSUE TITLE
% variance explained by PC1

### ISSUE THREAD

**Issue by esebesty** [ay-lab/dcHiC#24]
Hi, is it possible to get the % variance explained value for PC1 or PC2 using dcHiC results? A bit lost between the different intermediate files that dcHiC produces. Trying to produce a plot similar to 4B [here](https://genome.cshlp.org/content/23/2/260.long). If not, what would you recommend? Just run a regular R prcomp() + summary() on the normalized HiC counts and check the results? Thanks for any pointers!

**Comment by ay-lab** [comment]
Hello—we just launched the latest version. It would be great if you could check it out! 

For this particular question in this update, you will see that each replicate or sample will produce a chromosome wise *.rds file inside the *_pca folder. Then one can use that to calculate the variance like the following:

```
r <- readRDS("../../ES_NPC_100Kb_Comparison/ES_4_100Kb_pca/intra_pca/ES_4_100Kb_mat/chr9.svd.rds")
variance.explained <- prop.table(r$d^2)
variance.explained
[1] 0.95060248 0.04939752
```
