### ISSUE TITLE
functionsdchic.cpp:12:10: fatal error: BMAcc.h: No such file or directory

### ISSUE THREAD

**Issue by papelypluma** [ay-lab/dcHiC#25]
Hi dcHiC developers, I'd like to ask for help on installing functionsdchic_1.0.tar.gz. I've followed the instructions via Conda, and the following compilation error is encountered. Is there a way to address this issue?

> functionsdchic.cpp:12:10: fatal error: BMAcc.h: No such file or directory
>    12 | #include <BMAcc.h>

Thank you!

**Comment by ay-lab** [comment]
Hi! Thank you for using our tool. That is an interesting error—I don't think I have seen it before. What commands have you run for the download? Via conda it should only be a few: git clone, conda env create, conda activate, and then R CMD INSTALL dchicfunctions.

**Comment by The-Hungry-Caterpillar** [comment]
Hi, I also got this error, and so did my colleague.

I did:

```
git clone https://github.com/ay-lab/dcHiC
cd dcHiC
conda env create -f ./packages/dchic.yml
conda activate dchic
cd packages
R CMD INSTALL functionsdchic_1.0.tar.gz
```

Out:

```
... fatal error: BMAcc.h: No such file or directory
   12 | #include <BMAcc.h>
      |          ^~~~~~~~~
compilation terminated...
```

**Comment by papelypluma** [comment]
Hi @ay-lab. Thanks for looking into this. I followed exactly the steps and commands for conda just like what @The-Hungry-Caterpillar did.

**Comment by ay-lab** [comment]
Hi all, 

Thank you all for the notice and for using our tool. The issue seemed to be with the way that some header files were defined/included. Can you try the new file below? I tested it on Mac and Linux machines and it finished successfully. 

[functionsdchic_1.0.tar.gz](https://github.com/ay-lab/dcHiC/files/7588920/functionsdchic_1.0.tar.gz)

**Comment by papelypluma** [comment]
Hi @ay-lab. Thank you for sharing the file with us. It worked!

**Comment by The-Hungry-Caterpillar** [comment]
It works for me, too @ay-lab. Thank you so much!

**Comment by ay-lab** [comment]
Awesome—will push to main repo now!
