### ISSUE TITLE
dcHiC without replicates

### ISSUE THREAD

**Issue by papelypluma** [ay-lab/dcHiC#27]
Hi @ay-lab. I'd just like to ask how does the current version of dcHiC deal with data without replicates. The previous version of dcHiC (v1, in a separate branch) has the --repParams option that can be specified if replicates are not available. A trial run using the current master branch of dcHiC without replicates seems to work, but I'm just curious to know how does dcHiC work this one out internally?

Thank you.

**Comment by ay-lab** [comment]
Hi! Yes—it should run with or without replicates. In the backend, running with replicates will increase statistical power but either way dcHiC will produce results.

**Comment by papelypluma** [comment]
Thanks @ay-lab for the response! Just one last question. Is it safe to assume that in order to call for differential compartments, dcHiC uses the correlation difference between samples without replicates in addition to changes that can be observed in PC1?

**Comment by ay-lab** [comment]
I'm not exactly sure what that means, but with or without replicates, dcHiC: 1) uses mahalanobis distance (a multivariate z-score) to estimate the variation of compartment values for each bin and, 2) employs a chi-squared distribution with n-1 degrees of freedom to calculate its significance.

**Comment by papelypluma** [comment]
Hi @ay-lab. Thanks for the explanation! It a lot clearer now.
