### ISSUE TITLE
PC1 of one chr is chromosome arm

### ISSUE THREAD

**Issue by csijcs** [ay-lab/dcHiC#31]
Great tool!

I came across one issue. For a particular sample the PC1 is the comaprtment score for all chrs except one. For that chr PC1 came out as the chromosome arms. Is there an easy way to get PC2 for that chr only?

For all other chrs and for samples PC1 is accurate.

**Comment by ay-lab** [comment]
Thank you for the kind words! Have you looked at `reselectpc.r` (under /utility)? You can see more about it on this [wiki page](https://github.com/ay-lab/dcHiC/wiki/Re-selecting-PC's).

**Comment by csijcs** [comment]
Sorry, I didn't realize there was a "new" way of doing it. I was still doing it the "old" way (dchic.py). I will run through the new protocol/documentation. Out of curiosity, is there any way to recover PC2 from the old way?
