### ISSUE TITLE
How to run dcHiC without replicates

### ISSUE THREAD

**Issue by BenxiaHu** [ay-lab/dcHiC#36]
Hello,
    thanks for developing dcHiC analyzing Hi-C without replicates.
Running dcHiC Without Replicates
Differential calling with dcHiC "learns" the amount that PC (compartment) values vary between biological replicate datasets and uses those parameters for significance thresholds. However, it is also possible to run dcHiC from start to finish without replicates (for users using HiC-Pro, this means using the allValidPairs file).

In the **input.txt file**, put the same name for the "replicate" and "cell line" columns.

HMEC  HMEC    /path/to/HMEC
MCF7  MCF7    /path/to/MCF7
MCF10 MCF10   /path/to/MCF10

After building **input.txt file**, I am trying to running dchic.py, but got the following errors:

Traceback (most recent call last):
  **File "/data/software/dcHiC-dcHiCv2.0/dchic/run.py", line 421, in <module>
    filenum = int(file.split("_")[3].split(".")[0])
ValueError: invalid literal for int() with base 10: 'exp'**
python /data/software/dcHiC-dcHiCv2.0/dchic/makeBedGraph.py -eigfile chr_1/hmfa_HiC3-CD8T-Health2-Veh_combine_exp_1.txt -chr 1 -exp HiC3-CD8T-Health2-Veh_combine
Traceback (most recent call last):
  File "/data/software/dcHiC-dcHiCv2.0/dchic/makeBedGraph.py", line 40, in <module>
    with open(results.eigfile, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'chr_1/hmfa_HiC3-CD8T-Health2-Veh_combine_exp_1.txt'
python /data/software/dcHiC-dcHiCv2.0/dchic/makeBedGraph.py -eigfile chr_1/hmfa_HiC4-CD8T-Health2-GYY_combine_exp_2.txt -chr 1 -exp HiC4-CD8T-Health2-GYY_combine
Traceback (most recent call last):
  File "/data/software/dcHiC-dcHiCv2.0/dchic/makeBedGraph.py", line 40, in <module>
    with open(results.eigfile, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'chr_1/hmfa_HiC4-CD8T-Health2-GYY_combine_exp_2.txt'

**Comment by ay-lab** [comment]
Hi, thanks for using the dcHiC and yes, it is possible to run dcHiC without the replicates. The input.txt file should have four columns - 

matrix.file      bed.file      replicate_name      sample_name

For your case, this should be something like the following - 

HMEC.mat HMEC.bed HEMC HMEC_sample
MCF7.mat MCF7.bed MCF7 MCF7_sample
MCF10.mat MCF10.bed MCF10 MCF10_sample

Even if you don't have replicates, treat the sample as replicate (third column), and please make sure that the third and fourth column name is different (that is why I have added the "_sample" to the HiC names). 

Also, we had a major update to our code. So, please use the current version. Disregard it if you're using the latest version. 
Give it a try and let us know how it goes. We are happy to help!

**Comment by BioEpi** [comment]
Thanks a lot. Do I run the R version, not python version if using the latest version of dcHiC?

**Comment by ay-lab** [comment]
Do you have chrY or chrM in the bed files? 
Also, can you paste the input.txt file here and the column names of the intra_sample_chr9_combined.pcOri.bedGraph? I think the error is due to a naming mismatch!

**Comment by BioEpi** [comment]
NO, I have deleted chrX/Y/M in the bed files in advances. But I do not delete  chrX/Y/M from the matrix files.

input.txt file  has four columns, 
HMEC.mat HMEC.bed HEMC HMEC_sample
MCF7.mat MCF7.bed MCF7 MCF7_sample

**Comment by ay-lab** [comment]
Hi, thanks for pasting the files. Deleting the chromosomes from the bed file is good enough.  dcHiC can handle chrX, so there is no need to delete the chrX.  ChrY/M has too few reads and thus throws out an error, so it's a better idea to exclude them. 

I would suggest deleting the existing files/folders generated by dcHiC completely and trying running it again.  To save time and resources, dcHiC can detect existing files, and my guess is that it is doing the same here too.

**Comment by BioEpi** [comment]
I rerun it again, but the error is occured to again. I do not know which step is not correct.

**Comment by ay-lab** [comment]
I need to understand the data before I can help you further! If you look at the 'DifferentialResult/Health_vs_case_100Kb' folder you should see the following files - 

$ tree ./DifferentialResult/Health_vs_case_100Kb
|-- differential.intra_sample_chr10_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr11_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr12_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr13_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr14_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr15_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr16_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr17_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr18_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr19_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr20_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr21_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr22_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr1_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr2_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr3_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr4_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr5_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr6_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr7_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr8_combined.pcQnm.bedGraph
|-- differential.intra_sample_chr9_combined.pcQnm.bedGraph
|-- differential.intra_sample_chrX_combined.pcQnm.bedGraph
|-- differential.intra_sample_combined.Filtered.pcQnm.bedGraph
|-- differential.intra_sample_combined.pcQnm.bedGraph
|-- differential.intra_sample_group.Filtered.pcOri.bedGraph
|-- differential.intra_sample_group.Filtered.pcQnm.bedGraph
|-- differential.intra_sample_group.pcOri.bedGraph
`-- differential.intra_sample_group.pcQnm.bedGraph

Can you check your folder and let me know which files are missing? 
This will help me to point out the step where the program is failing!

**Comment by katecycho** [comment]
> I rerun it again, but the error is occured to again. I do not know which step is not correct.

Hi Benxia,
Do you by any chance remember how you fixed this issue? I am getting the same error. Thank you
