### ISSUE TITLE
error in pcselect step

### ISSUE THREAD

**Issue by adalgarno** [ay-lab/dcHiC#38]
Hi --

I've installed the software, extracted the data from .hic files (excluding all 'abnormal' chromosomes) according to the GitHub instructions (all files look as expected) and am now trying to run the overall script (adapted from the GitHub page):

Rscript dchicf.r --file pro_v_sen.txt --pcatype cis --dirovwt T --cthread 2 --pthread 4
Rscript dchicf.r --file pro_v_sen.txt --pcatype select --dirovwt T --genome hg38
Rscript dchicf.r --file pro_v_sen.txt --pcatype analyze --dirovwt T --diffdir pro_v_sen_100Kb
#Rscript dchicf.r --file pro_v_sen.txt --pcatype fithic --dirovwt T --diffdir pro_v_sen_100Kb --fithicpath "~/anaconda/dchic/bin/fithic" --pythonpath "~/anaconda/dchic/bin/python"
Rscript dchicf.r --file pro_v_sen.txt --pcatype dloop --dirovwt T --diffdir pro_v_sen_100Kb
Rscript dchicf.r --file pro_v_sen.txt --pcatype subcomp --dirovwt T --diffdir pro_v_sen_100Kb
Rscript dchicf.r --file pro_v_sen.txt --pcatype viz --diffdir pro_v_sen_100Kb --genome hg38
Rscript dchicf.r --file pro_v_sen.txt --pcatype enrich --genome hg38 --diffdir conditionA_vs_conditionB --exclA F --region both --pcgroup pcQnm --interaction intra --pcscore F --compare F

However, I am receiving the following error from the pcatype select (pcselect) step:
Running  intra   chr1  in  pro_v_sen_100kb  sample
Error in aggregate.data.frame(mf[1L], mf[-1L], FUN = FUN, ...) : 
  no rows to aggregate
Calls: pcselect ... aggregate -> aggregate.formula -> aggregate.data.frame
In addition: Warning messages:
1: In (function (..., deparse.level = 1)  :
  number of columns of result is not a multiple of vector length (arg 1)
2: In (function (..., deparse.level = 1)  :
  number of columns of result is not a multiple of vector length (arg 1)
Execution halted

Any ideas on how to fix this? Please let me know if you need any additional information. Thanks!

**Comment by ay-lab** [comment]
It seems like there is an issue with the input file format. Is it possible for you to provide a demo input file for the same? For the size issue, it can be of very low resolution but should be processed exactly like the one you're trying to process here. I like to recreate the issue from our side. If you want you can send the files to my email abhijit@lji.org

**Comment by adalgarno** [comment]
Sure! I can send you the input files over email. Thanks

**Comment by ay-lab** [comment]
Hi Audrey, 
I have used your file to run the pcselect step and successfully generated the output. Please check the other Hi-C file too, this one seems fine to me.

**Comment by ay-lab** [comment]
So, the error was related to data.table version and updating the package resolved the issue.
