### ISSUE TITLE
plot error

### ISSUE THREAD

**Issue by biozzq** [ay-lab/dcHiC#4]
Dear all,

I found that the dcHiC can not be finished smoothly, giving following standard error and the `ReplicateImages` directory is empty.
```
qt.qpa.xcb: could not connect to display login01:42.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.
```
According to the standard out, i need run following command to summarize the results (note that i have turned off the opinion `-makePlots`);
`python differentialCalling.py -inputFile input.txt -chrFile chr.txt -res 100000 -genome mm10 -blacklist mm10-blacklist.v2.bed`
 
If possible, can you save these figures but not visual.

Best wishes,
Zheng zhuqing

**Comment by ay-lab** [comment]
Hello,

I am not sure what the root of the error is here; the qt error appears to be coming from matplotlib being unable to "find" a display plugin. It should be noted, however, that these plots look like the image below; they are simply pairwise comparisons of all same-cell replicates to visualize the concordance in PC values between replicates. 

You can see these statistics in the "chrdistances.txt" file, which has the mean and standard deviation of replicate PC value variation from the fitted linear model. In general, values below 0.3-0.4 indicate good replicate concordance. 

![Chr9_replicates](https://user-images.githubusercontent.com/18036388/104947704-03829c80-5971-11eb-8f2f-5baf87d06a92.png)
