### ISSUE TITLE
Unknown genome id while open the html file

### ISSUE THREAD

**Issue by xinghua1001** [ay-lab/dcHiC#40]
Thank you for developing this tool.
I have finished running visualization without error and get the html file. However, it shows error when I open the html file.
My code is:
Rscript dchicf.r --file input_smed.txt --pcatype viz --diffdir smed_dchic_150Kb --gfolder smed_150000_goldenpathData --genome g4w.

Is it because the web IGV doesn't have my genome. How can I open it locally.

Thanks!

**Comment by ay-lab** [comment]
Hi, 

Thanks for trying out the tool. Yes, the standalone IGV package doesn't support the genome. 
You can use UCSC genome browser to visualize the data. 
And sorry for the late reply on this issue.
