### ISSUE TITLE
Make some files more unix-friendly

### ISSUE THREAD

**Issue by robomics** [ay-lab/dcHiC#45]
Hi,

It looks like some files (namely [dchic.r](https://github.com/ay-lab/dcHiC/blob/0f0a9449bf070c44b21aa53deed4dab3d3a4e8c3/dchicf.r) and [utility/reselectpc.r](https://github.com/robomics/dcHiC/commit/b05cc92514ac67447285df8c4549cd218ac8d583#diff-1a40195785b33e0fddce0d86d39231dd90633a13da616a5365f8ad3a787a23cd)) use '\r' instead of '\n' to mark end of lines.

This causes errors like `/usr/bin/env: ‘Rscript\r’: No such file or directory` when running e.g. `dchic.r` on Ubuntu.

Could you please run [dos2unix](https://linux.die.net/man/1/dos2unix) or a similar tool to replace '\r' with '\n'?

If you can't install the tool on your machines, feel free to grab the files from my fork [here](https://github.com/robomics/dcHiC/tree/run-dos2unix).

This is the command I used to run dos2unix on my fork:

```bash
find /tmp/dcHiC -type f -exec dos2unix -k -s -o {} \;
```

I was about to submit a PR with the fix, but decided against that because this change would make it look like I authored every single line in the incriminated files.

**Comment by ay-lab** [comment]
Thanks for you suggestion, we are working on it.

**Comment by ay-lab** [comment]
Hey Roberto, 

Thanks again for raising this issue; we really appreciate the PR's and code improvements you've been suggesting. I was surprised to see this issue—it seems like every file has \r \n? Not sure why this should cause an error.

In any case, I've updated the two files with the character removed. Please let me know if these work!

**Comment by robomics** [comment]
Thanks for the rapid fix! Works like a charm :)

Cheers!
