### ISSUE TITLE
Support for other genomes:

### ISSUE THREAD

**Issue by Nico-FR** [ay-lab/dcHiC#46]
Hello,

I would like to use dcHiC on cow.

However it is not clear how is made the TSS file. In the "Technical Specifications" section, you give an exemple for [hg38.tss.bed](https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/genes/hg38.refGene.gtf.gz) but it is a gtf file. 
Cow golden path: https://hgdownload.cse.ucsc.edu/goldenpath/bosTau9/bigZips/

So, how to make this tss.bed file ? 
Is it just a 2 columns table with chromosome, TSS position?
3 columns, chr, start and end?

Thanks

**Comment by Nico-FR** [comment]
Ok, I found the solution by analysing the code.

The .refGene.gtf.gz is needed and your script will generate the .tss.bed

You should mention it in the section to avoid that kind of issues.

**Comment by ay-lab** [comment]
Apologies about the lack of clarity. I just updated the documentation to reflect this!
