### ISSUE TITLE
hashmap

### ISSUE THREAD

**Issue by EnrichettaMileti** [ay-lab/dcHiC#49]
Hi!
I installed the latest version of dchic. Everything is fine but I can't install hashmap.
I'm using R version 3.6.1 and I saw that hashmap was build in version 3.2.1
When I tried to install on version 3.2.1 and I have the issue with the R library bigstatsr that I can't install for that R version.
Any suggestion?

**Comment by ay-lab** [comment]
Hi, 

For such cases, you can directly download the tar.gz file https://cran.r-project.org/src/contrib/bigstatsr_1.5.12.tar.gz and install it from the command line as - 
$ R CMD INSTALL bigstatsr_1.5.12.tar.gz 

Hopefully, this will resolve the issue unless bigstatr has other dependency issues. In that case, you probably need to install the packages one at a time or upgrade your R version. 

Let me know how it goes.

**Comment by EnrichettaMileti** [comment]
Thanks for your reply. An additional question: Which R version do you recommend to use for installing all the packages?
Thanks

**Comment by ay-lab** [comment]
I have tested this in R 3.3.3, and R 4.0. I also don't think you will have any issues in between.
