### ISSUE TITLE
How to locate the highly different compartment

### ISSUE THREAD

**Issue by biozzq** [ay-lab/dcHiC#5]
Dear all,

How can we locate the highly different compartment quickly, just by the lowest padj? Maybe you can explain the parameters for us, such as `mdist` and `dZsc`, which can help us to understand the results. Thank you.

![image](https://user-images.githubusercontent.com/15704257/104895989-8592b580-59b1-11eb-9992-4ae3aecc8744.png)

Best wishes,
Zheng Zhuqing

**Comment by ay-lab** [comment]
Hello,

Apologies for the lack of documentation on this subject; a pre-print is forthcoming and the GitHub descriptions have been updated. The Log10 PAdj (dark green) contains the FDR-adjusted p-values — use those for identifying significant differential compartments. Full data is available in the "full_compartment_details" and "differential_compartments" bedGraphs.

**Comment by biozzq** [comment]
Dear @ay-lab

I can not detect any A/B compartment transitions, most signals show variability in A/B compartment scores, like following screenshot. Maybe these results indicate the global folding patterns of chromosomes are highly similar between case and control?
<img width="1007" alt="捕获" src="https://user-images.githubusercontent.com/15704257/106245240-1fc2eb00-6247-11eb-9623-9c291f23a2db.PNG">

Best wishes,
Zheng zhuqing

**Comment by ay-lab** [comment]
Looking at this screenshot, it does appear that the compartments for your two runs are very similar (it almost seems like they are replicates); checking other chromosomes may confirm that.

**Comment by biozzq** [comment]
Dear @ay-lab 

Thank you. The other chromosomes are same with above screenshot. Thus, I need treat this as the variability in A/B compartment scores rather than A/B compartment transitions. Is this OK?

Best wishes,
zheng zhuqing

**Comment by ay-lab** [comment]
Yes—MFA normalization ensures that the scaling etc is normalized and the values are comparable

**Comment by biozzq** [comment]
Dear @ay-lab 

Thank you for your help. 

Best wishes,
Zheng zhuqing
