### ISSUE TITLE
error: Two levels of parallelism are used. See `?assert_cores`.

### ISSUE THREAD

**Issue by Woohootakeoff** [ay-lab/dcHiC#50]
error: Two levels of parallelism are used. See `?assert_cores`.

Plz reply.Ths.

:
Matrix dimension 1204 X 1204
Performing Z transformation      : complete!
Performing block wise correlation calculation    : complete!
Matrix dimension 6232 X 6232
Matrix dimension 880 X 880
Performing Z transformation      : complete!
Performing block wise correlation calculation    : complete!
Performing Z transformation      : complete!
Performing block wise correlation calculation    : complete!
Matrix dimension 5654 X 5654
Performing Z transformation      : complete!
Performing block wise correlation calculation    : complete!
Error in checkForRemoteErrors(val) :
  2 nodes produced errors; first error: Two levels of parallelism are used. See `?assert_cores`.
Calls: lapply ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted

**Comment by ay-lab** [comment]
How many cores are you using? 
As an alternative option you can disable and run dcHiC with '--cthread 1 --pthread 1'

**Comment by Woohootakeoff** [comment]
thanks for your reply!Now i have a new error:(. please help again.
in step 2:
this is my command:
Rscript dchicf.r --file dchic_code.txt --pcatype select --dirovwt T --genome hg19
and this is my dchic_code.txt :
/E_40000_ym.matrix E_40000_abs_ym.bed E_40k exp1
K_40000_ym.matrix K_40000_abs_ym.bed K_40k exp2
and this is error:
Running  intra   chr1  in  E_40k  sample
Running  intra   chr2  in  E_40k  sample
Error in hclust(as.dist(round(1 - cor(pc.mat), 4))) :
  NA/NaN/Inf in foreign function call (arg 10)
Calls: pcselect -> pcselectioncore -> hclust
Execution halted

as u see , it can run chr1,2 successfully ,then crash.
and i can run STEP 1  " cis " successfully.

thanks for your help:))))))

**Comment by ay-lab** [comment]
Seems like it fails at the chr3 step. Can you check the chr3 PC values of E_40k, K_40k? The error may arise due to non-numerical values in the compartment score or noticed any anomalies in the compartment score (You can plot that too)? 

Also to confirm that it is not due to a Hi-C resolution-specific issue, can you please run your dataset at 100Kb?

**Comment by ay-lab** [comment]
Great! Happy to help you.
