### ISSUE TITLE
`numberclust` parameter

### ISSUE THREAD

**Issue by YichaoOU** [ay-lab/dcHiC#51]
Hi,

The default value for `numberclust` is 1, if I increase it to `2`, then no more significant compartments, which is what I want.

My question is that, based on your description on `Compartment clustering`, it makes sense to remove `lone differential compartments`. But is it OK to just change `numberclust` and keep `distclust` as default (`-1`)?

Thanks,
Yichao

**Comment by ay-lab** [comment]
Yes, please use distclust as -1, you can ignore that part. If you want to cluster the differential compartment and merge continuous lone peaks, you can simple use the merge option from bedtools. In our Nat comm dcHiC paper, we never merged the lone peaks and used as it is.

**Comment by YichaoOU** [comment]
Thanks!
