### ISSUE TITLE
Error: upper value must be greater than lower value Execution halted

### ISSUE THREAD

**Issue by KunFang93** [ay-lab/dcHiC#52]
Hi,

Thanks for providing this useful tool! I meet a error 
```
Performing block wise correlation calculation	Error: upper value must be greater than lower value Execution halted
```
when I tried to run 
```
Rscript /data/kun/Softwares/dcHiC/demo/dcHiC_demo/scripts/dchicf.r --file input.NT_PT_RT.txt --pcatype cis --dirovwt T --cthread 1 --pthread 1
```
It looks like this error arises from generating chrY.pca.txt. I attached the files related to generate chrY.pca.txt. Thanks for your help!

[chrY.txt](https://github.com/ay-lab/dcHiC/files/10559580/chrY.txt)
[chrY.precmat.txt](https://github.com/ay-lab/dcHiC/files/10559581/chrY.precmat.txt)
[chrY.bed.txt](https://github.com/ay-lab/dcHiC/files/10559602/chrY.bed.txt)
[chrY.distparam.txt](https://github.com/ay-lab/dcHiC/files/10559603/chrY.distparam.txt)

Best,
Kun

**Comment by ay-lab** [comment]
Hello,

In our analysis, we omitted chromosome Y. It is poorly mapped and compartments from this chromosome are of poor quality; we've had quite a few issues with this in the [past](https://github.com/ay-lab/dcHiC/issues?q=is%3Aissue+chrY) as well. Would that work?

**Comment by KunFang93** [comment]
Got it, I will try to remove chrY and re-run chic, thanks!

**Comment by KunFang93** [comment]
Remove chrY from .matrix and .bed works, thanks!
