### ISSUE TITLE
running dhHiC on nf-core hic pipeline output file

### ISSUE THREAD

**Issue by chklopp** [ay-lab/dcHiC#55]
Hi,

The nf-core hicpro pipeline (https://nf-co.re/hic/usage) generates compartment files  : 

Results are available in results/compartments/ folder and includes :
    *cis.vecs.tsv: eigenvectors decomposition along the genome
    *cis.lam.txt: eigenvalues associated with the eigenvectors

How can we analyze these files with dhHiC?

**Comment by jeffreyywangg** [comment]
Hello! You should be able to take the eigenvectors along the genome and plug them into dcHiC with just a bit of reformatting — see this [page](https://github.com/ay-lab/dcHiC/wiki/Using-Existing-PC-Values-with-dcHiC) about using existing PC's with dcHiC. You will likely be using `intra` as your PC type, and the replicate/sample relationships can be read about in the main README (see how to format the input file). 

Before doing this, I would also check to make sure your PC's are correctly oriented (i,e. that the signs are not flipped along a particular chromosome).
