### ISSUE TITLE
  cis interaction matrix    and trans interaction matrix

### ISSUE THREAD

**Issue by Zheng19w** [ay-lab/dcHiC#56]
cis | Find compartments on a cis interaction matrix
-- | --
trans | Find compartments on a trans interaction matrix

Dear professor:
I used hicpro to get valid.paris, Next I'll use the "build_matrix" executable under the IC -Pro utilities folder, first create the sparse matrix/bed files for each replicate's validPairs, first create the sparse matrix/bed files for each replicate's validpairs, Then how did cis interaction matrix and trans interaction matrix appear, was it not a sparse matrix?

**Comment by ay-lab** [comment]
Hi! Thank you for using our tool.

I'm not sure if I completely follow the first question—the output of `build_matrix` is exactly the sparse matrix/bed files that can be input to dcHiC (with paths specified in the input file). Let me know if that clears things up, or if your question is different. 

The matrices in this figure were visualized with a standard visualization tool (you could use Juicebox or any number of Hi-C matrix viewing tools); the tracks on top with loops and significant compartments were made using the `viz` feature of our tool. You can see web-hosted examples [here](https://ay-lab.github.io/dcHiC/).

**Comment by Zheng19w** [comment]
Thank you for your recovery. I would like to know in which step cis interaction matrix and trans interaction matrix are generated.
What are the effects of these two matrices on the downstream analysis



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/10/2023 23:28 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ay-lab/dcHiC] cis interaction matrix and trans interaction matrix (Issue #56) |

Hi! Thank you for using our tool.

I'm not sure if I completely follow the first question—the output of build_matrix is exactly the sparse matrix/bed files that can be input to dcHiC (with paths specified in the input file). Let me know if that clears things up, or if your question is different.

The matrices in this figure were visualized with a standard visualization tool (you could use Juicebox or any number of Hi-C matrix viewing tools); the tracks on top with loops and significant compartments were made using the viz feature of our tool. You can see web-hosted examples here.

**Comment by Zheng19w** [comment]
Second question, for example, with juicerbox, how do you input two hics at the same time and display them on the lower left side and the upper right side of the same picture, thank you



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/10/2023 23:28 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ay-lab/dcHiC] cis interaction matrix and trans interaction matrix (Issue #56) |

Hi! Thank you for using our tool.

I'm not sure if I completely follow the first question—the output of build_matrix is exactly the sparse matrix/bed files that can be input to dcHiC (with paths specified in the input file). Let me know if that clears things up, or if your question is different.

The matrices in this figure were visualized with a standard visualization tool (you could use Juicebox or any number of Hi-C matrix viewing tools); the tracks on top with loops and significant compartments were made using the viz feature of our tool. You can see web-hosted examples here.

**Comment by ay-lab** [comment]
1) `build_matrix` is just a utility to convert your Hi-C Pro processed data into sparse matrix/bed formats. dcHiC does not generate the cis or trans interaction matrices; it takes them as input data. In the `cis` or `trans` step, it will use those sparse matrix/bed files and run compartment analysis on them. 

Regarding the effects of these on downstream analysis, recall that `cis` interaction matrices are _intra_-chromosomal interactions and `trans` interactions are _inter_-chromosomal interactions (which are much sparser). Compartment analysis as it is usually defined uses `cis` interactions, and we'd recommend doing this at least as your first round of analyses, since it will generate the most standard/interpretable results. 

2) You can't display two matrices top and bottom on Juicebox; we stitched those two images together for the figure. If you want to generate those two figures, run "observed" and "O/E" modes on Juicebox.

**Comment by Zheng19w** [comment]
Thank you very much for your help. Is build matrix a built-in program of hicpro



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/11/2023 00:43 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ay-lab/dcHiC] cis interaction matrix and trans interaction matrix (Issue #56) |

build_matrix is just a utility to convert your Hi-C Pro processed data into sparse matrix/bed formats. dcHiC does not generate the cis or trans interaction matrices; it takes them as input data. In the cis or trans step, it will use those sparse matrix/bed files and run compartment analysis on them.

Regarding the effects of these on downstream analysis, recall that cis interaction matrices are intra-chromosomal interactions and trans interactions are inter-chromosomal interactions (which are much sparser). Compartment analysis as it is usually defined uses cis interactions, and we'd recommend doing this at least as your first round of analyses, since it will generate the most standard/interpretable results.

You can't display two matrices top and bottom on Juicebox; we stitched those two images together for the figure. If you want to generate those two figures, run "observed" and "O/E" modes on Juicebox.

**Comment by ay-lab** [comment]
Yes -- it should be an executable in Hi-C Pro!

**Comment by Zheng19w** [comment]
![image](https://user-images.githubusercontent.com/106860091/218233871-da2f5369-40a4-4bb3-9af5-6b504f1b869c.png)
Thank you for your reply. In this article, when you analyze ABcompartment changes, would you use cis interaction matrix or trans interaction matrix, or aggregate the results of both

**Comment by ay-lab** [comment]
Please use the cis interaction!

**Comment by Zheng19w** [comment]
Thank you for your reply.
