### ISSUE TITLE
Genome selection problem

### ISSUE THREAD

**Issue by Zheng19w** [ay-lab/dcHiC#57]
Dear professor: 
I'm looking for your help again,
Official guide: Rscript dchicf.r --file input.ES_NPC.txt --pcatype select --dirovwt T --genome mm10

But the species I'm studying is pigs, not humans and mouse or other model animals, so how do I choose?

**Comment by Zheng19w** [comment]
second question:
--genome=GENOME
                Genome name, e.g. hg38/hg19/mm10/mm9 
                [default NONE, should be provided by the user]


        
--gfolder=GFOLDER
                Genome folder path, e.g. <genome>_<resolution>_goldenpathData folder (This folder should contain three files - <genome>.fa, <genome>.tss.bed and <genome>.chrom.sizes files) 
                [default NA]

when to use the -- gfolder parameter, How to generate .tss.bed, the species is  pig

**Comment by ay-lab** [comment]
Take a look at our documentation, where the "support for other genomes" should answer your question. You should specify the genome name with `--genome` and name `--gfolder` correspondingly. 

You can fine the relevant files for the genome folder under the UCSC bigZips [directory](https://hgdownload.soe.ucsc.edu/goldenPath/susScr11/bigZips/), with the .tss.bed file under /genes as the `refGene` [file](https://hgdownload.soe.ucsc.edu/goldenPath/susScr11/bigZips/genes/susScr11.refGene.gtf.gz).

**Comment by Zheng19w** [comment]
Thank you very much for your help, this is a very good tool, thank you for answering my questions, wish you a good weekend!



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/11/2023 23:13 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ay-lab/dcHiC] Genome selection problem (Issue #57) |

Take a look at our documentation, where the "support for other genomes" should answer your question. You should specify the genome name with --genome and name --gfolder correspondingly.

You can fine the relevant files for the genome folder under the UCSC bigZips directory, with the .tss.bed file under /genes as the refGenefile.

**Comment by Zheng19w** [comment]
I have another question. I used hicpro and constructed the reference genome index of pigs from ensembl database with boetie2, does it have any effect to use the relevant files of ucsc now? I directly download ref.gene.gtf.gz. Can it be used directly as tff.bed?



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/11/2023 23:13 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ay-lab/dcHiC] Genome selection problem (Issue #57) |

Take a look at our documentation, where the "support for other genomes" should answer your question. You should specify the genome name with --genome and name --gfolder correspondingly.

You can fine the relevant files for the genome folder under the UCSC bigZips directory, with the .tss.bed file under /genes as the refGenefile.

**Comment by ay-lab** [comment]
Yes, the refGene file can directly be used as the .tss.bed file.

**Comment by Zheng19w** [comment]
thank you for your help ,but I used hicpro and constructed the reference genome index of pigs from ensembl database with boetie2, does it have any effect to use the relevant files of ucsc now?
Can I use the gtf comment file corresponding to the genome ensembl database, which I use as tss.bed-gz




---- Replied Message ----
| From | ***@***.***> |
| Date | 02/12/2023 05:54 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ay-lab/dcHiC] Genome selection problem (Issue #57) |

Yes, the refGene file can directly be used as the .tss.bed file.

**Comment by Zheng19w** [comment]
thank you for your help ,but I used hicpro and constructed the reference genome index of pigs from ensembl database with boetiw2, does it have any effect to use the relevant files of ucsc now?
Can I use the gtf comment file corresponding to the genome ensembl database, which I use as tss.bed-gz



---- Replied Message ----
***@***.***>Date02/12/2023 ***@***.***>***@***.***>***@***.***>SubjectRe: [ay-lab/dcHiC] Genome selection problem (Issue #57)
Yes, the refGene file can directly be used as the .tss.bed file.

**Comment by ay-lab** [comment]
Please use the UCSC genome and gtf file. It will have no effect on your downstream analysis. dcHiC uses genome fasta file and gtf file to calculate GC content and TSS correlation. This correlation is used for A/B compartment assignment.

**Comment by Zheng19w** [comment]
Thank you for your answer. Thank you very much.



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/12/2023 14:45 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ay-lab/dcHiC] Genome selection problem (Issue #57) |

Please use the UCSC genome and gtf file. It will have no effect on your downstream analysis. dcHiC uses genome fasta file and gtf file to calculate GC content and TSS correlation. This correlation is used for A/B compartment assignment.
