### ISSUE TITLE
how to define signicantly differential compartment switch

### ISSUE THREAD

**Issue by biohubx** [ay-lab/dcHiC#6]
Hi,
   when I checked out the _differential_compartments.bedGraph_ file generated by dcHiC, the number of differential compartments is about 100. However, when I extracted significantly differential compartments at the FDR of 0.05 0r  0.01, from _**full_compartment_details.bedGraph**_, the number of significantly differential compartments is greater than 1000.

Could you explain to me how dcHiC output the _differential_compartments.bedGraph_ file?

Another question: How to define High B and low B?
for example, the PC scores in a given region between 2 different conditions (tumor and normal) are -4 and -1, respectively.  So the tumor in this region is defined as High B or Low B?

Best,

**Comment by ay-lab** [comment]
Hello,

Apologies about the delayed reply. "High B" is defined as a strong B compartment (-4) and "low B" is defined as a weak B compartment (-1). If your tumor is -4, it has stronger B compartmentalization ("high B) compared to your normal cell line. 

With regard to the differential calling—thank you for pointing out the discrepancy. It seems that a small deprecated feature wasn't properly updated; the numbers should now match if you use the latest "diffcmp_pythonV.R" file in the GitHub.
