### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by Lucas446** [ay-lab/dcHiC#65]
Hi, 

If I want to plot the A/B compartment as matrices which output file would you use ?

Also could explain the role of the following files, and the ones that can be used to visualize the results:
chrX.bed
chrX.cmat.txt
chrX.distparam
chrX.pc.bedGraph
chrX.pc.txt
chrX.PC1.bedGraph
chrX.PC2.bedGraph
chrX.precmat.txt
chrX.svd.rds

Best,

**Comment by jeffreyywangg** [comment]
What do you mean by matrices? You can use `-viz` to get tracks that look like [this](https://ay-lab.github.io/dcHiC/hematopoiesis_100Kb.RefineY_Rconf90_FDR10.pcOri.html). This uses a file created from `-analyze` after differential calling is run. 

If you want to visualize compartments on an axis with the underlying Hi-C matrix (e.g. Fig A [here](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.researchgate.net%2Ffigure%2FCharacterization-of-A-B-compartments-a-Pearson-correlation-matrix-The-plaid-pattern_fig2_317389565&psig=AOvVaw1HSqtc5B60Je9UdDqRc_A_&ust=1680897539155000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCOCjwbeFlv4CFQAAAAAdAAAAABAa)), you could use Juicebox, upload the .hic file, and add PC1.bedGraph (or PC2 if e.g. PC1 captures a chromosome arm). 

Re: which file to use from the options you listed, by default, dcHiC tries to output just about anything you might want from the intermediate levels; for instance, .svd.rds is the R binary dump of the SVD. The PC files are the ones you'll want for viz: .pc.txt and .pc.bedGraph have results for all PC's, and .PC1.bedGraph and .PC2.bedGraph just contain data for the specified PC. Use whichever format works best for your purposes!

**Comment by Lucas446** [comment]
I see, thanks for the explanations. 

Concerning the matrices, I was wondering if there is a way to extract the HiC contact map of a sample after distance normalization step ? In order to extract normalized contact value at various position stored in a .bed file for example ?

best,

**Comment by Lucas446** [comment]
Also, concerning PC1 and 2, I realized that dcHiC is taking PC1, which clearly capture chr arms, for differential analysis, is there a way to force it to take PC2 ?

**Comment by jeffreyywangg** [comment]
Sorry about the late response - I don't think dcHiC currently outputs that map because it's so memory-expensive, but plenty of other tools (e.g. HOMER) do this!

dcHiC doesn't take PC1 by default; it tries to intelligently select the "best" PC, but sometime it gets this wrong. You can see PC assignments in an output text file—and re-select by using a utility (see [this](https://github.com/ay-lab/dcHiC/wiki/Re-selecting-PC's) wiki page).

**Comment by Lucas446** [comment]
Hi, 

Concerning the PC1 and 2, here is the result of compartment if PC1 or PC2 are selected:
PC1:
<img width="1265" alt="Screen Shot 2023-04-10 at 1 24 10 PM" src="https://user-images.githubusercontent.com/46545862/230956709-909ff4e1-ee7f-4f1b-a6b9-51f00db19c01.png">

PC2: 
<img width="1263" alt="Screen Shot 2023-04-10 at 1 24 16 PM" src="https://user-images.githubusercontent.com/46545862/230956820-b26b5c83-31be-43b8-a9ae-5a9d417fd4cb.png">

Do think that it is more accurate to force select PC2 is that case ?

Thanks a lot,
Best,

**Comment by jeffreyywangg** [comment]
Hmmm... these are really poor-looking PC's. I'm unsure how interpretable these results are. I'm only familiar with mice/human data from my own experimentation and it seems like this a different genome; is this more or less what you expected to see for compartments? Or were you looking for something with less noise? 

I might try looking at other PC's (3/4) or finding different data.

**Comment by abhijitcbio** [comment]
Please set the `--pc` option to 4 during the `pca` step. It will generate PC's up to 4. 
Also, what is the Hi-C resolution you're using to analyze the compartments?

**Comment by Lucas446** [comment]
Ok I will try to look at the other PCA. The resolution I am using is 20kb. (HiC from 10'000 cells, dpnII, biotin step, around 4 millions valid pairs per replicates)

**Comment by Lucas446** [comment]
Here are the PC1,2,3,4 for chr2L. I feel that PC2 is the best here, what do you think ?

<img width="1835" alt="Screen Shot 2023-04-12 at 4 37 58 PM" src="https://user-images.githubusercontent.com/46545862/231578808-7296a9d0-7221-4043-91c6-bc2c875b1437.png">




If I change resolution 20kb to 50kb, I get less noise, as expected: 
2 first rows are 20kb for 2 time points, 2 last rows are same time point at 50kb resolution

<img width="1840" alt="Screen Shot 2023-04-12 at 4 32 25 PM" src="https://user-images.githubusercontent.com/46545862/231577850-459454b9-a87e-4af5-ae42-c60d35d32cce.png">

**Comment by ay-lab** [comment]
Yes, the PC2 is way better. In any case, using a low resolution always improves the compartment calls.
