### ISSUE TITLE
dcHIC --pcatype analyze: dim(X) must have a positive length

### ISSUE THREAD

**Issue by Lucas446** [ay-lab/dcHiC#66]
Hi, 

I re-analyzing data from GSE130545. I processed it using HiC-Pro and now analyzing A/B compartment with dcHiC.

However, at the --pcatype analyze step I get this error:

```
Rscript /Users/tlucas/dcHiC/dchicf.r --file input.txt --pcatype analyze --dirovwt T --diffdir diff_analysis
Running intra sample differential calls for  S2_HiC  samples
Wrote  DifferentialResult/diff_analysis/S2_HiC_data/intra_2L_combined.pcOri.bedGraph and pcQnm.bedGraph files
Wrote  DifferentialResult/diff_analysis/S2_HiC_data/intra_2R_combined.pcOri.bedGraph and pcQnm.bedGraph files
Wrote  DifferentialResult/diff_analysis/S2_HiC_data/intra_3L_combined.pcOri.bedGraph and pcQnm.bedGraph files
Wrote  DifferentialResult/diff_analysis/S2_HiC_data/intra_3R_combined.pcOri.bedGraph and pcQnm.bedGraph files
Wrote  DifferentialResult/diff_analysis/S2_HiC_data/intra_X_combined.pcOri.bedGraph and pcQnm.bedGraph files
Error in apply(abs(chrom_sample_qn), 2, mean) : 
  dim(X) must have a positive length
Calls: pcanalyze -> apply
Execution halted
```

Do you know what could cause this issue ? 

Here are all the file to re create the issue: https://wetransfer.com/downloads/d947d7d61e3632fca3c7cebdca62618e20230412164701/0d615feae653d8d38c8dc1db03589a2720230412164738/80a4b2?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid

Best,

**Comment by ay-lab** [comment]
I have looked at your files. Your input.txt file has only one sample. 
For `--pcatype analyze` step you will need at least two samples for differential comparison.
Are you trying to compare two samples?

**Comment by Lucas446** [comment]
Oh I see my bad... I wanted to look at PCA for this unique sample, obviously the differential will not go through :) Sorry for that!
