### ISSUE TITLE
--pcatype cis crashing

### ISSUE THREAD

**Issue by wkc1986** [ay-lab/dcHiC#71]
This step keeps crashing:

```
Performing Z transformation: complete!
Performing block wise correlation calculation        Error: upper value must be greater than lower value
```

Can you offer any advice? Thank you.

**Comment by ay-lab** [comment]
It can crash if you have non-standard chromosomes like chrY/chrM and others. Please try to remove those instances from the bed file and give it another shot. Let me know how it goes.

**Comment by wkc1986** [comment]
Yes, this was due to leftover files from a failed run from which chrX had not been omitted. Thanks.
