### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by haizi-zh** [ay-lab/dcHiC#8]
https://github.com/ay-lab/dcHiC/blob/6af6d0e8d6c4c31b597f4bd502246c7fe90bbf3c/dchic/pcselect.r#L15

Here it should be:

```
cytoband <- paste0("curl -O http://hgdownload.cse.ucsc.edu/goldenPath/",genome,"/database/cytoBand.txt.gz")
```

**Comment by ay-lab** [comment]
Fixed!
