### ISSUE TITLE
error in hclust (--pcatype select)

### ISSUE THREAD

**Issue by katecycho** [ay-lab/dcHiC#84]
Hello!

I am facing an error in the second step, --pcatype select. The first step with --cis works fine, but I am also trying to rerun it. This is my code:` Rscript dchicf.r --file input.txt --pcatype select --dirovwt T --genome hg38`
And the error happens in my first sample file: 
![Screenshot 2024-01-02 at 9 14 49 AM](https://github.com/ay-lab/dcHiC/assets/116030375/9f4be7a8-f164-4e8e-86f5-c4cec7ffc4d1)

It seems like chr6 in my first sample is raising an issue. As suggested in [https://github.com/ay-lab/dcHiC/issues/47](url) and [https://github.com/ay-lab/dcHiC/issues/50](url), I plotted my PC1 and PC2 values. 
PC1 plots: 
![pc1](https://github.com/ay-lab/dcHiC/assets/116030375/b817d13e-5952-460c-a21b-86ccca211021)

PC2 plots:  
![d775729c-f370-4aa8-a388-27a4fb051c45](https://github.com/ay-lab/dcHiC/assets/116030375/208fba67-690f-41ed-9133-4f892cb5dba4)

Could you advise me what the issue may be? The current resolution is 50kb so I can also try 100kb, or even reselect PC. Thank you so much in advance.

**Comment by ay-lab** [comment]
Hi, 

Is it only the IDHwt1 sample that is causing this issue or the other ones too?
Can you manually look at the chr6 PC1/PC2 files and see if the values look normal/numerical?

**Comment by katecycho** [comment]
Thank you for your reply.
It seems that not having added blacklist caused the result. Now it's running fine! Thank you so much.

**Comment by ay-lab** [comment]
Great!
