### ISSUE TITLE
In function `geneEnrichment`, the "pcQnm" bedgraph is loaded when `pcgrp `= "pcOri" — is this correct?

### ISSUE THREAD

**Issue by kalavattam** [ay-lab/dcHiC#86]
Hi all,

Thanks again for making and maintaining this great tool. I have a question about the code associated with the function `geneEnrichment` in [dchicf.r](https://github.com/ay-lab/dcHiC/blob/master/dchicf.r).

At lines [2384–2387](https://github.com/ay-lab/dcHiC/blob/master/dchicf.r#L2384-L2387), we see the following, in which variable `pcgrp` defaults to "pcOri" (non-quantile-normalized score values) when variable `exclA` is set to `FALSE`:
```r
if (exclA == FALSE & pcgrp == "pcQnm") {
	pcgrp <- "pcOri"
	cat ("exclA is set to False, changing pcgroup from pcQnm to pcOri\n")
}
```

In lines [2444–2471](https://github.com/ay-lab/dcHiC/blob/master/dchicf.r#L2444-L2471), we see the "pcQnm" (quantile-normalized score values) bedgraph file is loaded rather than the "pcOri" bedgraph, despite `pcgrp` being set to "pcOri":
```r
if (exclA == FALSE & pcgrp == "pcOri") {
	compartment_score_pcQnm <- read.table(paste0("DifferentialResult/",diffdir,"/fdr_result/differential.",interaction,"_sample_group.pcQnm.bedGraph"), h=T, as.is=T)
	diff_compartments_pcQnm <- read.table(paste0("DifferentialResult/",diffdir,"/fdr_result/differential.",interaction,"_sample_group.Filtered.pcQnm.bedGraph"), h=T, as.is=T)
	rownames(compartment_score_pcQnm) <- paste0(compartment_score_pcQnm$chr,"_",compartment_score_pcQnm$start)
	rownames(diff_compartments_pcQnm) <- paste0(diff_compartments_pcQnm$chr,"_",diff_compartments_pcQnm$start)
...
```

I just want to double check if this is intentional. Thank you.

**Comment by ay-lab** [comment]
Hi, 

Thanks for catching the issue. I have fixed and updated the code with the proper files. You can download the code and rerun it. Although, this shouldn't cause any difference in the result. As the exclA option was set to false, dcHiC is only checking if the pc-score of a sample is higher than rest of the samples. This should be true regardless of the file used given it is compared within the same category. Thanks again for catching this.

**Comment by kalavattam** [comment]
Makes sense. Thanks again!
