### ISSUE TITLE
issue with html 

### ISSUE THREAD

**Issue by katecycho** [ay-lab/dcHiC#89]
Hello,

I am not sure if this is issue with my connection but the html site seems to not be working. It doesn't work on the html I generated, nor the example html [page](https://ay-lab.github.io/dcHiC/ESC_NPC_100Kb.RefineY_Rconf90_FDR10.pcOri.html). I attached what i see on my screen.

![Screenshot 2024-01-24 at 2 05 11 PM](https://github.com/ay-lab/dcHiC/assets/116030375/25bb97cc-c8c7-4bda-8870-550842a8aa5c)

Thank you

**Comment by ay-lab** [comment]
Thanks for reporting this. We are also facing the issue. 
We are trying to investigate the problem. It might be an issue from the IGV site, too.
We are looking into it.

**Comment by ay-lab** [comment]
Hi, 

It's back to normal now. 
It was indeed an IGV issue. 
Thanks again for informing us.
