### ISSUE TITLE
Question regarding enrich

### ISSUE THREAD

**Issue by RomeroMatt** [ay-lab/dcHiC#90]
Hello,
Thanks for the great tool. I have been learning how to use dchic on my existing Hi-C dataset. But I am a bit confused on one parameter. for the code below:
`Rscript dchicf.r --file input.txt --pcatype enrich --genome mm10 --diffdir conditionA_vs_conditionB --exclA F --region both --pcgroup pcQnm --interaction intra --pcscore F --compare F
` 
Do I need to run fithic and dloop prior to running --pcatype enrich? I interpreted the instructions as though you can look at gene enrichment in differential compartments, independent of loops. Am I misinterpreting this step? I was able to run all the steps prior to the optional ones, but when I run the enrich step, it asks for a bedpe file. Please see the error code below:

Finding gene enrichment for  hPSC hPSC_SMPC Fetal_SMPC  samples
[1] "hPSC"       "hPSC_SMPC"  "Fetal_SMPC"   
exclA is set to False, changing pcgroup from pcQnm to pcOri
[1] "hg38_500000_goldenpathData"
Error in file(file, "rt") : cannot open the connection
Calls: geneEnrichment -> read.table -> file  
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'DifferentialResult/hPSC_hPSC_SMPC_Fetal_SMPC_500kb/fdr_result/differential.intra_compartmentLoops.bedpe': No such file or directory
Execution halted

Any insight would be helpful. Thanks!

-Matt

**Comment by ay-lab** [comment]
Hi, 

Thanks for using the tool, and yes you can look at gene enrichment in differential compartments. 

Please change the "--region both" option to "--region anchor" to do the same. 

Let me know if you face any other issues.

**Comment by RomeroMatt** [comment]
Thank you! Looking back, I completely misinterpreted that option. I got it to work and I was able to make figures. Thanks!
