### ISSUE TITLE
pca select error: hclust 

### ISSUE THREAD

**Issue by katecycho** [ay-lab/dcHiC#92]
Hello,

Sorry to be raising so many issues. I am re-running dchic on selected samples from the previous run, but this time grouping them as replicates (3 groups, ~30 samples total). They ran fine on the past run so I am not sure what the issue is but I keep getting this error. I have removed the blacklist and chrX, and have tried at 50kb and 100kb res. 

`Rscript dchicf.r --file input.txt --pcatype select --dirovwt T --genome hg38
`
Do you have any idea how I could troubleshoot? I have attached my input file and pictures of the error. 
<img width="649" alt="Screenshot 2024-02-27 at 10 28 21 PM" src="https://github.com/ay-lab/dcHiC/assets/116030375/72200db7-29dd-41c6-af3f-4146bbf8e132">
![Screenshot 2024-02-28 at 8 44 03 AM](https://github.com/ay-lab/dcHiC/assets/116030375/f0636ab0-3602-4df9-937c-9360f86acc1c)
[input.txt](https://github.com/ay-lab/dcHiC/files/14437541/input.txt)

**Comment by ay-lab** [comment]
Do you have the <genome_size_goldenpathData> folder? Can you list the files inside that directory? 

Also, when you're rerunning, please make sure you don't have any old-run files. It's a good idea to start fresh, otherwise dchic can fetch any existing file.

**Comment by katecycho** [comment]
![Screenshot 2024-02-28 at 11 51 48 AM](https://github.com/ay-lab/dcHiC/assets/116030375/42db20cb-a1b8-416a-9e2c-69cfc65a251d)

Ok. I only used the same .matrix and .bed files in a new folder but I can also re-generate them. Thank you
