### ISSUE TITLE
Can't get --bdgfile flag to work.

### ISSUE THREAD

**Issue by RomeroMatt** [ay-lab/dcHiC#93]
Hello,
Thanks again for the great tool. I've been able to get most everything to work. I am having difficulty with one thing and that is the viz option. I am trying to add RNA-seq bedgraph files to the html file, but it will not add them for some reason. My command is:
`Rscript dchicf.r --file input_merged_hPSC_hPSC_SMPC_Fetal_SMPC_500kb.txt --pcatype viz --diffdir merged_hPSC_hPSC_SMPC_Fetal_SMPC_500kb --genome hg38 --pcgroup pcQnm --bdgfile /data/dcHiC/bedgraph/bedgraphInfo_all.txt`

My bedgraphInfo_all.txt file is a four column file with the layout as described in the help menu:
<path to bedGraph>	<name>	<type>	<pos color:neg color>
where my path is: path/to/folder/, ex: /data/dcHiC/bedgraph/
name: name of file w/o .bedgraph extension, ex: AP9-W17_1
type: bedgraph
pos color:neg color: 250,0,0:0

The html is made, but just without the RNA-seq bedgraph file. Any help would be wonderful!
-Matt

**Comment by ay-lab** [comment]
So, here is one of my demo bdgfile looks like - 
```
mESC.TPM.bedGraph       ES_TPM  bedGraph        255,55,118:0
NPC.TPM.bedGraph        NPC_TPM bedGraph        1,182,138:0
```

Please use 'bedGraph' instead of 'bedgraph' in the file and try again. I hope this will resolve the issue. 

Sorry if I have mistyped it in the help menu.

**Comment by RomeroMatt** [comment]
Excellent! This worked - thanks a ton!
