### ISSUE TITLE
pcatype enrich gene list error

### ISSUE THREAD

**Issue by katecycho** [ay-lab/dcHiC#96]
Hello! 

I was able to successfully run dchic and thank you again for this tool. In running --pcatype enrich, I continue getting warning message 
Code: `Rscript dchicf.r --file input.txt --pcatype enrich --genome hg38 --diffdir dir --exclA T --region anchor --pcgroup pcQnm --interaction intra --pcscore F --compare F
`
Warning: `There are way to many genes overlapping with the A compartment, the command line option has return an error! Please mannually upload the gene list.`

This is output of a folder within the geneEnrichment folder. 
![Screenshot 2024-03-11 at 10 40 21 AM](https://github.com/ay-lab/dcHiC/assets/116030375/19be6d18-d042-42d8-b4e2-57d0cbbb41fc)

Could you please help me navigate through the files and how to extract the necessary information?

Thank you again so much for the help.

**Comment by ay-lab** [comment]
This is an issue from the https://toppgene.cchmc.org/enrichment.jsp side. 
dcHiC uses its API function to upload the gene list and perform enrichment, but if it is too big, it fails. 
I would suggest you to perform the gene enrichment using their site directly or using whatever your favorite tool is.

**Comment by katecycho** [comment]
Got it- thank you!!
