### ISSUE TITLE
error at pcatype=cis level

### ISSUE THREAD

**Issue by Sagnik-Epigen** [ay-lab/dcHiC#98]
I encountered "Performing block wise correlation calculation	Error: upper value must be greater than lower value"  this error. Please suggest. I have tried 50K,100K, 1MB resolution.

**Comment by ay-lab** [comment]
Please check the input you're providing. 
dcHiC accepts a three-column hic interaction file like the following - 

1 2 10 
1 3 8 
.. 

The first two columns are the indices of the genomic region provided in the bed file, and the third column represents the interaction count. 

The first column index must be less than or equal to the second column index number. If it is not than it will raise the error.

**Comment by Sagnik-Epigen** [comment]
yeah basic the .matrix file from hicpro output. right?

**Comment by ay-lab** [comment]
Yes

**Comment by Sagnik-Epigen** [comment]
I tried your suggestion. However it is still showing errors. 
if using --ebackgrnd=2
Error in aggregate.data.frame(lhs, mf[-1L], FUN = FUN, ...) : 
  no rows to aggregate
Calls: lapply ... aggregate -> aggregate.formula -> aggregate.data.frame
if using --ebackgrnd=1
Performing block wise correlation calculation Error: upper value must be greater than lower value
error

**Comment by ay-lab** [comment]
Can you just check this `awk '$1 > $2 { print }' <matrix file> |wc -l `

**Comment by Sagnik-Epigen** [comment]
Tried that and modified the matrix file as per your last instructions.

**Comment by ay-lab** [comment]
Great! Let me know if you face any other issues.
